-- CreateTable
CREATE TABLE "NationalPark" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "wiki" TEXT NOT NULL,
    "wikiUrl" TEXT NOT NULL,
    "wikiInputToken" INTEGER,
    "wikiOutputToken" INTEGER,
    "wikiUrlToken" INTEGER,
    "wikiProcessTime" DOUBLE PRECISION,
    "officialWebsite" TEXT NOT NULL,
    "officialWebsiteSourceText" TEXT NOT NULL,
    "officialWebsiteSourceUrl" TEXT NOT NULL,
    "level" INTEGER NOT NULL,
    "levelSourceText" TEXT NOT NULL,
    "levelSourceUrl" TEXT NOT NULL,
    "speciesCount" INTEGER NOT NULL,
    "speciesCountSourceText" TEXT NOT NULL,
    "speciesCountSourceUrl" TEXT NOT NULL,
    "endangeredSpecies" INTEGER NOT NULL,
    "endangeredSpeciesSourceText" TEXT NOT NULL,
    "endangeredSpeciesSourceUrl" TEXT NOT NULL,
    "forestCoverage" DOUBLE PRECISION NOT NULL,
    "forestCoverageSourceText" TEXT NOT NULL,
    "forestCoverageSourceUrl" TEXT NOT NULL,
    "area" DOUBLE PRECISION NOT NULL,
    "areaSourceText" TEXT NOT NULL,
    "areaSourceUrl" TEXT NOT NULL,
    "establishedYear" INTEGER NOT NULL,
    "establishedYearSourceText" TEXT NOT NULL,
    "establishedYearSourceUrl" TEXT NOT NULL,
    "internationalCert" INTEGER NOT NULL,
    "internationalCertSourceText" TEXT NOT NULL,
    "internationalCertSourceUrl" TEXT NOT NULL,
    "annualVisitors" INTEGER NOT NULL,
    "annualVisitorsSourceText" TEXT NOT NULL,
    "annualVisitorsSourceUrl" TEXT NOT NULL,

    CONSTRAINT "NationalPark_pkey" PRIMARY KEY ("id")
);
