export const progress = [
  { name: 'Afghanistan', done: true },
  { name: 'Albania', done: false },
  { name: 'Algeria', done: false },
  { name: 'American Samoa', done: false },
  { name: 'Angola', done: false },
  { name: 'Argentina', done: false },
  { name: 'Armenia', done: false },
  { name: 'Ascension Island', done: false },
  { name: 'Australia', done: false },
  { name: 'Austria', done: false },
  { name: 'Azerbaijan', done: false },
  { name: 'Bahamas', done: false },
  { name: 'Bangladesh', done: false },
  { name: 'Belarus', done: false },
  { name: 'Belgium', done: false },
  { name: 'Belize', done: false },
  { name: 'Benin', done: false },
  { name: 'Bhutan', done: false },
  { name: 'Bolivia', done: false },
  { name: 'Bosnia and Herzegovina', done: false },
  { name: 'Botswana', done: false },
  { name: 'Brazil', done: false },
  { name: 'Brunei', done: false },
  { name: 'Bulgaria', done: false },
  { name: 'Burkina Faso', done: false },
  { name: 'Burundi', done: false },
  { name: 'Cambodia', done: false },
  { name: 'Cameroon', done: false },
  { name: 'Canada', done: false },
  { name: 'Cape Verde', done: false },
  { name: 'Central African Republic', done: false },
  { name: 'Chad', done: false },
  { name: 'Chile', done: false },
  { name: 'China', done: false },
  { name: 'Colombia', done: false },
  { name: 'Comoros', done: false },
  { name: 'Cook Islands', done: false },
  { name: 'Costa Rica', done: false },
  { name: "Côte d'Ivoire", done: false },
  { name: 'Croatia', done: false },
  { name: 'Curacao', done: false },
  { name: 'Czech Republic', done: false },
  { name: 'Democratic Republic of the Congo', done: false },
  { name: 'Denmark', done: false },
  { name: 'Djibouti', done: false },
  { name: 'Dominica', done: false },
  { name: 'Dominican Republic', done: false },
  { name: 'Ecuador', done: false },
  { name: 'Egypt', done: false },
  { name: 'El Salvador', done: false },
  { name: 'Equatorial Guinea', done: false },
  { name: 'Eritrea', done: false },
  { name: 'Estonia', done: false },
  { name: 'Eswatini', done: false },
  { name: 'Ethiopia', done: false },
  { name: 'Fiji', done: false },
  { name: 'Finland', done: false },
  { name: 'France', done: false },
  { name: 'Gabon', done: false },
  { name: 'Gambia', done: false },
  { name: 'Georgia', done: false },
  { name: 'Germany', done: false },
  { name: 'Ghana', done: false },
  { name: 'Greece', done: false },
  { name: 'Guatemala', done: false },
  { name: 'Guinea', done: false },
  { name: 'Guinea-Bissau', done: false },
  { name: 'Kazakhstan', done: false },
  { name: 'Kenya', done: false },
  { name: 'Kosovo', done: false },
  { name: 'Kyrgyzstan', done: false },
  { name: 'Latvia', done: false },
  { name: 'Lebanon', done: false },
  { name: 'Liberia', done: false },
  { name: 'Libya', done: false },
  { name: 'Lithuania', done: false },
  { name: 'Madagascar', done: false },
  { name: 'Malawi', done: false },
  { name: 'Malaysia', done: false },
  { name: 'Maldives', done: false },
  { name: 'Mauritius', done: false },
  { name: 'Mexico', done: false },
  { name: 'Moldova', done: false },
  { name: 'Mongolia', done: false },
  { name: 'Montenegro', done: false },
  { name: 'Morocco', done: false },
  { name: 'Mozambique', done: false },
  { name: 'Myanmar', done: false },
  { name: 'Namibia', done: false },
  { name: 'Nepal', done: false },
  { name: 'Netherlands', done: false },
  { name: 'New Zealand', done: false },
  { name: 'Nicaragua', done: false },
  { name: 'Niger', done: false },
  { name: 'Nigeria', done: false },
  { name: 'North Macedonia', done: false },
  { name: 'Norway', done: false },
  { name: 'Oman', done: false },
  { name: 'Pakistan', done: false },
  { name: 'Panama', done: false },
  { name: 'Papua New Guinea', done: false },
  { name: 'Paraguay', done: false },
  { name: 'Peru', done: false },
  { name: 'Philippines', done: false },
  { name: 'Poland', done: false },
  { name: 'Portugal', done: false },
  { name: 'Qatar', done: false },
  { name: 'Republic of China (Taiwan)', done: false },
  { name: 'Republic of the Congo', done: false },
  { name: 'Romania', done: false },
  { name: 'Russia', done: false },
  { name: 'Rwanda', done: false },
  { name: 'Samoa', done: false },
  { name: 'Saudi Arabia', done: false },
  { name: 'Senegal', done: false },
  { name: 'Serbia', done: false },
  { name: 'Seychelles', done: false },
  { name: 'Sierra Leone', done: false },
  { name: 'Slovakia', done: false },
  { name: 'Slovenia', done: false },
  { name: 'Solomon Islands', done: false },
  { name: 'Somalia', done: false },
  { name: 'South Africa', done: false },
  { name: 'South Korea', done: false },
  { name: 'Spain', done: false },
  { name: 'Sri Lanka', done: false },
  { name: 'Sudan', done: false },
  { name: 'Sweden', done: false },
  { name: 'Switzerland', done: false },
  { name: 'Tanzania', done: false },
  { name: 'Thailand', done: false },
  { name: 'Timor-Leste', done: false },
  { name: 'Togo', done: false },
  { name: 'Tunisia', done: false },
  { name: 'Turkey', done: false },
]
