export const progress = [
  { name: 'Afghanistan', done: true },
  { name: 'Albania', done: true },
  { name: 'Algeria', done: true },
  { name: 'American Samoa', done: true },
  { name: 'Angola', done: true },
  { name: 'Argentina', done: true },
  { name: 'Armenia', done: true },
  { name: 'Ascension Island', done: true },
  { name: 'Australia', done: true },
  { name: 'Austria', done: true },
  { name: 'Azerbaijan', done: true },
  { name: 'Bahamas', done: true },
  { name: 'Bangladesh', done: true },
  { name: 'Belarus', done: true },
  { name: 'Belgium', done: true },
  { name: 'Belize', done: true },
  { name: 'Benin', done: true },
  { name: 'Bhutan', done: true },
  { name: 'Bolivia', done: true },
  { name: 'Bosnia and Herzegovina', done: true },
  { name: 'Botswana', done: true },
  { name: 'Brazil', done: true },
  { name: 'Brunei', done: true },
  { name: 'Bulgaria', done: true },
  { name: 'Burkina Faso', done: true },
  { name: 'Burundi', done: true },
  { name: 'Cambodia', done: true },
  { name: 'Cameroon', done: true },
  { name: 'Canada', done: true },
  { name: 'Cape Verde', done: true },
  { name: 'Central African Republic', done: true },
  { name: 'Chad', done: true },
  { name: 'Chile', done: true },
  { name: 'China', done: true },
  { name: 'Colombia', done: true },
  { name: 'Comoros', done: true },
  { name: 'Cook Islands', done: true },
  { name: 'Costa Rica', done: true },
  { name: "Côte d'Ivoire", done: true },
  { name: 'Croatia', done: true },
  { name: 'Curacao', done: true },
  { name: 'Czech Republic', done: true },
  { name: 'Democratic Republic of the Congo', done: true },
  { name: 'Denmark', done: true },
  { name: 'Djibouti', done: true },
  { name: 'Dominica', done: true },
  { name: 'Dominican Republic', done: true },
  { name: 'Ecuador', done: true },
  { name: 'Egypt', done: true },
  { name: 'El Salvador', done: true },
  { name: 'Equatorial Guinea', done: true },
  { name: 'Eritrea', done: true },
  { name: 'Estonia', done: true },
  { name: 'Eswatini', done: true },
  { name: 'Ethiopia', done: true },
  { name: 'Fiji', done: true },
  { name: 'Finland', done: true },
  { name: 'France', done: true },
  { name: 'Gabon', done: true },
  { name: 'Gambia', done: true },
  { name: 'Georgia', done: true },
  { name: 'Germany', done: true },
  { name: 'Ghana', done: true },
  { name: 'Greece', done: true },
  { name: 'Guatemala', done: true },
  { name: 'Guinea', done: true },
  { name: 'Guinea-Bissau', done: true },
  { name: 'Guyana', done: true },
  { name: 'Haiti', done: true },
  { name: 'Honduras', done: true },
  { name: 'Hungary', done: true },
  { name: 'Iceland', done: true },
  { name: 'India', done: true },
  { name: 'Indonesia', done: true },
  { name: 'Iran', done: true },
  { name: 'Ireland', done: true },
  { name: 'Israel', done: true },
  { name: 'Italy', done: true },
  { name: 'Japan', done: true },
  { name: 'Jordan', done: true },
  { name: 'Kazakhstan', done: true },
  { name: 'Kenya', done: true },
  { name: 'Kosovo', done: true },
  { name: 'Kyrgyzstan', done: true },
  { name: 'Latvia', done: true },
  { name: 'Lebanon', done: true },
  { name: 'Liberia', done: true },
  { name: 'Libya', done: true },
  { name: 'Lithuania', done: true },
  { name: 'Madagascar', done: true },
  { name: 'Malawi', done: true },
  { name: 'Malaysia', done: true },
  { name: 'Maldives', done: true },
  { name: 'Mauritius', done: true },
  { name: 'Mexico', done: true },
  { name: 'Moldova', done: true },
  { name: 'Mongolia', done: true },
  { name: 'Montenegro', done: true },
  { name: 'Morocco', done: true },
  { name: 'Mozambique', done: true },
  { name: 'Myanmar', done: true },
  { name: 'Namibia', done: true },
  { name: 'Nepal', done: true },
  { name: 'Netherlands', done: true },
  { name: 'New Zealand', done: true },
  { name: 'Nicaragua', done: true },
  { name: 'Niger', done: true },
  { name: 'Nigeria', done: true },
  { name: 'North Macedonia', done: true },
  { name: 'Norway', done: true },
  { name: 'Oman', done: true },
  { name: 'Pakistan', done: true },
  { name: 'Panama', done: true },
  { name: 'Papua New Guinea', done: true },
  { name: 'Paraguay', done: true },
  { name: 'Peru', done: true },
  { name: 'Philippines', done: true },
  { name: 'Poland', done: true },
  { name: 'Portugal', done: true },
  { name: 'Qatar', done: true },
  { name: 'Republic of China (Taiwan)', done: true },
  { name: 'Republic of the Congo', done: true },
  { name: 'Romania', done: true },
  { name: 'Russia', done: true },
  { name: 'Rwanda', done: true },
  { name: 'Samoa', done: true },
  { name: 'Saudi Arabia', done: true },
  { name: 'Senegal', done: true },
  { name: 'Serbia', done: true },
  { name: 'Seychelles', done: true },
  { name: 'Sierra Leone', done: true },
  { name: 'Slovakia', done: true },

  { name: 'Slovenia', done: true },
  { name: 'Solomon Islands', done: true },
  { name: 'Somalia', done: true },
  { name: 'South Africa', done: true },
  { name: 'South Korea', done: true },
  { name: 'Spain', done: true },
  { name: 'Sri Lanka', done: true },
  { name: 'Sudan', done: true },
  { name: 'Sweden', done: true },
  { name: 'Switzerland', done: true },
  { name: 'Tanzania', done: true },
  { name: 'Thailand', done: true },
  { name: 'Timor-Leste', done: true },
  { name: 'Togo', done: true },
  { name: 'Tunisia', done: true },
  { name: 'Turkey', done: true },
  { name: 'Uganda', done: true },
  { name: 'Ukraine', done: true },
  { name: 'United Arab Emirates', done: true },
  { name: 'United Kingdom', done: true },
  { name: 'United States', done: true },

  { name: 'Uruguay', done: true },
  { name: 'US Virgin Islands', done: true },
  { name: 'Uzbekistan', done: true },
  { name: 'Venezuela', done: true },
  { name: 'Vietnam', done: true },
  { name: 'Yemen', done: true },
  { name: 'Zambia', done: true },
  { name: 'Zimbabwe', done: true },
]
